dataloader_params:
  data_path: './data'
  batch_size: 12500

q_net_params:
  width_list: [64, 64]
  box: [0.0, 10.0]

u_net_params:
  width_list: [64, 64]
  box: 'none'

loss_params:
  alpha: 1.0
  lamb: 1.0e-7

pretrain_optim_params:
  pretrain_u_lr: 1.0e-3
  pretrain_u_reg: 0.0

optim_params_adam:
  q_lr: 1.0e-4
  u_lr: 1.0e-4
  name: 'adam'
  options: 
    weight_decay: 0.0

optim_params_lbfgs:
  q_lr: 0.2
  u_lr: 0.2
  name: 'lbfgs'
  options: 
    max_iter: 50
    tolerance_grad: 1.0e-7
    tolerance_change: 1.0e-12
    history_size: 100
    line_search_fn: 'strong_wolfe'

scheduler_params:
  warmup_steps: 1000
  total_steps: 10000
  cosine_annealing: false

train_params:
  pretrain_epochs_u: 20
  num_epochs: [50, 9950]
  results_path: './output/'

task:
  idx: '03'
  noise_str: '10'